### ISSUE TITLE
Set a translated content to blank

### ISSUE THREAD

**Issue by jloosfelt** [globalize/globalize-accessors#20] opened 2015-05-05 15:25 UTC
On Rail 4.2.0 and globalize-accessors 0.2.0, we have an issue: when the user validates the form with a blank value, the update is ignored.
We tried to understand but we think that it might involve globalize-accessors.

In console:

    Page.first.update_attributes {content_fr: nil, content_en: nil}

Will erase the content in both fr and en.

But in controller, the exact same instruction (for the test I hard coded this instead of using the strong parameters) will ignore the change.

```ruby
class Page < ActiveRecord::Base
  translates :title, :content
  globalize_accessors :locales => [:fr, :en], :attributes => [:title, :content], accept_blank: true
end
```

I don't have this problem on 0.1.5 version of globalize-accessors.
Any idea?

**Comment by miks** [comment] 2015-05-12 21:23
Duplicate of #16. We need to get rid of that "empty value prevention" logic...

**Closed** 2015-05-12 22:05 UTC
