### ISSUE TITLE
Prevent empty localizations

### ISSUE THREAD

**Issue by firedev** [globalize/globalize-accessors#16] opened 2015-01-12 02:03 UTC
I have posted it to Globalize initially https://github.com/globalize/globalize/issues/397 but I think it belongs here.

I have a form that might have empty locales and they are being stored in database which is really annoying. Is there a way to prevent that?

I had a cleaner once that was removing blank keys from params hash, but can't find where I had it and thought somebody might have solved this once and for all.

Thinking louder, I would say if there is a translation present for the given language and and empty one is submitted - the exisiting one should be deleted from the database.

```
=> Tour.last.translations
  Tour Load (0.3ms)  SELECT  `tours`.* FROM `tours`  ORDER BY `tours`.`position` DESC LIMIT 1
  Tour::Translation Load (0.4ms)  SELECT `tour_translations`.* FROM `tour_translations` WHERE `tour_translations`.`tour_id` = 12
=> [
  [0] #<Tour::Translation:0x00000109f4d170> {
             :id => 12,
        :tour_id => 12,
         :locale => :en,
     :created_at => Sat, 03 Jan 2015 13:09:12 ICT +07:00,
     :updated_at => Sat, 03 Jan 2015 16:54:22 ICT +07:00,
          :title => "Whatever",
    :description => "Ut voluptatem sit delectus nisi alias dignissimos rerum."
  },
  [1] #<Tour::Translation:0x00000109f4d008> {
             :id => 28,
        :tour_id => 12,
         :locale => :es,
     :created_at => Sat, 03 Jan 2015 16:54:22 ICT +07:00,
     :updated_at => Sat, 03 Jan 2015 16:54:22 ICT +07:00,
          :title => "",
    :description => ""
  },
  [2] #<Tour::Translation:0x00000109f4ce50> {
             :id => 29,
        :tour_id => 12,
         :locale => :zh,
     :created_at => Sat, 03 Jan 2015 16:54:22 ICT +07:00,
     :updated_at => Sat, 03 Jan 2015 16:54:22 ICT +07:00,
          :title => "",
    :description => ""
  }
]
```

**Comment by firedev** [comment] 2015-01-19 14:33
Here is what I have at the moment:

```ruby
# config/initializers/globalize.rb
module Globalize
  module ActiveRecord
    class Translation
      after_save :clean_up

      def clean_up
        self.class.where(title: '').delete_all
      end
    end
  end
end
```

**Comment by tritter** [comment] 2015-02-01 11:12
Here is what I am doing... Please check my fork: tritter/globalize-accessors.

I created another method that checks if all attributes are blanks. And after that it deletes the translation record. I think the place where I put it is the wrong one because its not really a setter... This should definitely be added as an option in a new release.... Because I'm currently working on an web application where I want to rely on the db translations if there is one available. Or you should create a custom getter that is checking if a value is blank... But I think the DB approach is more reliable and safer.

My define setter:
`  def define_setter(attr_name, locale)
    localized_attr_name = localized_attr_name_for(attr_name, locale)

    define_method :"delete_translation_if_all_blank" do |locale|
      should_delete = true
      translated_attributes.keys.each do |key|
        should_delete = translation_for(locale)[key].blank?
        break if not should_delete
      end
      if should_delete
        translations.where(:locale => locale).delete_all()
        reload()
      end
    end

    define_method :"#{localized_attr_name}=" do |value|
      return if !translation_for(locale,false) && value.blank?
      write_attribute(attr_name, value, :locale => locale)
      translation_for(locale)[attr_name] = value
      delete_translation_if_all_blank(locale)
    end

    if respond_to?(:accessible_attributes) && accessible_attributes.include?(attr_name)
      attr_accessible :"#{localized_attr_name}"
    end
    self.globalize_attribute_names << localized_attr_name.to_sym
  end`

**Comment by eljojo** [comment] 2015-02-10 10:58
hi, I think this was fixed in https://github.com/globalize/globalize-accessors/pull/14 which was included in ``0.2.0``, released earlier this month

**Comment by tritter** [comment] 2015-02-13 14:15
Sorry yes a part is updated accordingly. I was using the older rails 4.0.2 with the older version of globalise. 

My version does still a better job when updating/removing existing translations with empty strings (so replacing an existing translation with an blank string, should remove it from the DB in my case). 

I'm using javascript to show/hide different languages in a form; by toggling visibility and input values(set to empty string) to delete translations.

**Comment by miks** [comment] 2015-04-19 20:47
Can we do something for this? Maybe option for empty translation creation preventing?
For now current solution is broken. As @tritter has stated "translation_caches" check is not working in all situations. I would rather to remove this "empty value prevention" at all, as there is no fail-safe solution to implemented it and it's up to controller/external logic to prevent empty value assigning.

**Comment by miks** [comment] 2015-04-26 08:08
Maybe `accept_blank` configuration option can solve this "pseodo problem"?
``` globalize_accessors :locales => [:en, :pl], :attributes => [:title], accept_blank: true``

**Comment by miks** [comment] 2015-05-12 21:25
@parndt Can we do something with this?

**Comment by parndt** [comment] 2015-05-12 22:06
@miks I hope so! I agree that it's up to the controller or external logic to prevent empty values from being provided to be saved, so what can we do?

**Comment by miks** [comment] 2015-05-13 05:49
@parndt see #21

**Comment by parndt** [comment] 2015-05-13 21:44
@miks do you think it's worth mentioning in the README that we do nothing about this?

**Comment by miks** [comment] 2015-05-14 05:46
No, because it's unexpected behaviour anyway.

**Closed** 2015-05-14 05:46 UTC

**Comment by Extrapolator214** [comment] 2016-03-18 09:43
@tritter I've rewritten your setter. `reload()` was so inconvenient, it prevented new translations from being created. Caching stuff.
```
module Globalize::Accessors
  def define_setter(attr_name, locale)
    localized_attr_name = localized_attr_name_for(attr_name, locale)

    define_method :"delete_translation_if_all_blank" do |locale|
      should_delete = true
      translated_attributes.keys.each do |key|
        should_delete = translation_for(locale)[key].blank?
        break if not should_delete
      end
      if should_delete
        translations.where(:locale => locale).delete_all()
      end
    end

    define_method :"#{localized_attr_name}=" do |value|
      if translation_for(locale,false)
        if value.blank?
          translation_for(locale)[attr_name] = value
          delete_translation_if_all_blank(locale)
        end
      else
        unless value.blank?
          write_attribute(attr_name, value, :locale => locale)
          translation_for(locale)[attr_name] = value
        end
      end
    end

    if respond_to?(:accessible_attributes) && accessible_attributes.include?(attr_name)
      attr_accessible :"#{localized_attr_name}"
    end
    self.globalize_attribute_names << localized_attr_name.to_sym
  end
end
```

**Comment by michelson** [comment] 2016-05-18 01:04
Hello , so currently there is no way to remove blank translations on this gem ?
I've seen that #21 removes the ability to handle blank translations, 
what was wrong with it ?

best

**Comment by davideghz** [comment] 2017-10-26 12:29
+1
